apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, PATCH, DELETE"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
        - path: /red(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: catalog-service
              port: 
                number: 9100
        - path: /blue
          pathType: Exact
          backend:
            service:
              name: hello-world-clusterip
              port: 
                number: 80
